### ISSUE TITLE
Feature Request: Add a Reset Button

### ISSUE THREAD

**Issue by ShashikaVirajh** [Gimnath-Perera/mocktopus#15]
It would be beneficial to have a reset button that can take the app to it's initial state.

**_User Experience:_** Enables a user to start fresh without having to manually clear the content.

**_Placement_**: Ideally near the Generate button.

This feature would enhance the user's overall experience and efficiency with the app.

**Comment by gimnathperera** [comment]
This is great. Do you like to make a PR on this ?
